version: '3.1'
services:
  mongo:
    image: mongo:4.4.1
    container_name: mongo
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aid3g7g21nklan
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: aid3g7g21nklan
    ports:
      - 8081:8081
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
networks:
  mongo-compose-network:
    driver: bridge